FROM jupyter/scipy-notebook
MAINTAINER Jupyter Project <jupyter@googlegroups.com>

COPY fix-permissions /usr/local/bin/fix-permissions
# Install Kernel Gateway
RUN pip install --upgrade pip && \
    pip install jupyter-kernel-gateway && \
    pip install docker && \
    pip install dulwich --global-option="--pure"
# fix permissions
USER root
RUN chmod a+x /usr/local/bin/fix-permissions
##    fix-permissions /home/jovyan/faas
USER jovyan
# add some files needed
COPY wrnaz wrnaz
#COPY faas.ipynb faas.ipynb

#RUN pwd && ls -la faas
# Configure container startup
ENTRYPOINT ["tini", "--", "jupyter-kernelgateway", "--KernelGatewayApp.api=notebook-http", "--KernelGatewayApp.ip=0.0.0.0", "--KernelGatewayApp.port=7777"]
CMD ["--KernelGatewayApp.seed_uri=./warren/faas/faas.ipynb"]


